# This workflow will run tests using node and then continuous integration when a pull request is created
# This file was contributed by Edwin Betancourt from ERP Consultores y Asociados, C.A

name: CI

# Triggers the workflow on pull request events but for the all branches
on: pull_request

jobs:

  # Build dist application ADempiere-Vue
  build-app:
    name: Test and Build ADempiere-Vue
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Node configuration
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Run test
        run: npm test

      - name: Compile dist
        run: npm run build:prod --if-present

      - name: Upload dist app
        uses: actions/upload-artifact@v2
        with:
          name: adempiere-vue
          path: dist
